import { NextRequest, NextResponse } from "next/server";
import { prisma, setRlsContext } from "@/lib/db";
import { requireUser } from "@/lib/auth";
import { loadExamDto } from "@/lib/serialize";
import { buildContext, generateTextCandidates, generatePartOneCandidates, generateTextExplorationCandidates, generateWritingCandidates, generateRewriteCandidates, validateCandidate, providerName } from "@/lib/generate";
import { track } from "@/lib/events";
import { captureRevision } from "@/lib/revisions";
import { getGuide } from "@/data/guides";
import type { GeneratedSource, GeneratedTask, GeneratedTopic } from "@/types";

function textOnly(candidate: { title: string; text: string }): { title: string; text: string } {
  return { title: candidate.title, text: candidate.text };
}

const DEFAULT_SOURCE: GeneratedSource = {
  title: "Exai original passage",
  author: null,
  publication: null,
  url: null,
  adaptationNote: "Original passage generated by Exai. No external source was used for this draft.",
  isExternal: false,
};

function sourceKey(source: GeneratedSource): string {
  return [source.title, source.author ?? "", source.publication ?? "", source.url ?? "", source.adaptationNote].join("|");
}

// A citation is obligatory for every generated text (PRD 2.4): providers that
// return none fall back to the "no external source" note. Distinct citations are
// kept so the teacher can pick one from the source dropdown.
async function persistSources(
  examId: string,
  sectionId: string,
  candidateSources: (GeneratedSource | null)[],
  isRegeneration: boolean
): Promise<void> {
  const resolved = candidateSources.map((s) => s ?? DEFAULT_SOURCE);
  const unique = new Map<string, GeneratedSource>();
  for (const source of resolved) unique.set(sourceKey(source), source);

  if (!isRegeneration) {
    await prisma.source.deleteMany({ where: { examId, sectionId } }).catch(() => {});
  } else {
    const existing = await prisma.source.findMany({ where: { examId, sectionId } });
    for (const row of existing) {
      unique.delete(
        sourceKey({
          title: row.title ?? "",
          author: row.author,
          publication: row.publication,
          url: row.url,
          adaptationNote: row.adaptationNote ?? "",
          isExternal: row.isExternal,
        })
      );
    }
  }

  const accessedAt = new Date().toISOString().slice(0, 10);
  for (const source of unique.values()) {
    await prisma.source.create({
      data: {
        examId,
        sectionId,
        title: source.title,
        author: source.author ?? null,
        publication: source.publication ?? null,
        url: source.url ?? null,
        accessedAt,
        adaptationNote: source.adaptationNote,
        isExternal: source.isExternal,
      },
    });
  }
}

function sectionHeading(grade: string, type: string, language?: string | null, stream?: string | null): string {
  const guide = getGuide(grade, language ?? "en", stream ?? undefined);
  if (type === "PART_ONE") return guide.headings?.partOne ?? "A. Reading Comprehension";
  if (type === "TEXT_EXPLORATION") return guide.headings?.textExploration ?? guide.textExploration.heading;
  if (type === "WRITING") return guide.headings?.writing ?? "C. Written expression";
  return "A. Reading Comprehension";
}

export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const user = await requireUser();
    await setRlsContext(user.id);
    const { id } = await params;
    const exam = await prisma.exam.findFirst({
      where: { id, userId: user.id },
      include: { config: true, sections: { include: { tasks: true, topics: true } } },
    });
    if (!exam) return NextResponse.json({ error: "Exam not found." }, { status: 404 });
    if (!exam.config) return NextResponse.json({ error: "Set the exam parameters first." }, { status: 400 });

    const body = (await req.json()) as { type: string; taskId?: string; topicId?: string; target?: "simpler" | "harder" };
    const type = body.type;
    const provider = providerName();

    const ctx = buildContext({
      level: exam.config.level,
      grade: exam.config.grade,
      stream: exam.config.stream,
      length: exam.config.length,
      unit: exam.config.unit,
      topic: exam.config.topic,
      examId: exam.id,
      language: exam.config.language,
      teacherKeywords: exam.config.teacherKeywords ?? null,
      difficulty: exam.config.difficulty ?? null,
    });

    const log = (status: string, error?: string) =>
      prisma.generation.create({ data: { examId: id, type, provider, status, error } });

    const sectionOf = (sections: any[], type: string) =>
      sections.find((s: any) => s.type === type);

    if (type === "TEXT") {
      const candidates = await generateTextCandidates(ctx);
      const v = validateCandidate("TEXT", { text: candidates[0].text, title: candidates[0].title });
      if (!v.ok) {
        await log("ERROR", v.issues.join("; "));
        await track("generation_failed", { userId: user.id, examId: id, meta: { type, issues: v.issues } });
        return NextResponse.json({ error: v.issues.join(" ") }, { status: 422 });
      }
      let section = sectionOf(exam.sections, "TEXT");
      if (!section) {
        section = await prisma.examSection.create({
          data: { examId: id, type: "TEXT", heading: sectionHeading(exam.config.grade, "TEXT", exam.config.language, exam.config.stream), order: 1, content: "{}" },
        });
      }
      const current = section.content ? JSON.parse(section.content) : {};
      const isRegeneration = !!current.text;
      // "Generate another text" never overwrites approved work: new versions land
      // in the alternatives box and the teacher selects one explicitly (PRD 15.2).
      const content = isRegeneration
        ? { ...current, candidates: [...(current.candidates ?? []), ...candidates.map(textOnly)] }
        : { ...current, title: candidates[0].title, text: candidates[0].text, candidates: candidates.slice(1).map(textOnly) };
      await prisma.examSection.update({
        where: { id: section.id },
        data: { content: JSON.stringify(content) },
      });
      await persistSources(id, section.id, candidates.map((c) => c.source ?? null), isRegeneration);
      await log("OK");
      await track("text_generated", { userId: user.id, examId: id, meta: { mode: isRegeneration ? "regenerate" : "first" } });
      await captureRevision(id, isRegeneration ? "Text alternatives generated" : "Text generated");
    } else if (type === "PART_ONE" || type === "TEXT_EXPLORATION") {
      const sets = type === "PART_ONE" ? await generatePartOneCandidates(ctx) : await generateTextExplorationCandidates(ctx);
      const guideMarks = type === "PART_ONE" ? ctx.guide.marks.partOne : ctx.guide.marks.textExploration;
      const v = validateCandidate(type, sets[0], guideMarks, { guide: ctx.guide });
      if (!v.ok) {
        await log("ERROR", v.issues.join("; "));
        await track("generation_failed", { userId: user.id, examId: id, meta: { type, issues: v.issues } });
        return NextResponse.json({ error: v.issues.join(" ") }, { status: 422 });
      }
      let section = sectionOf(exam.sections, type);
      if (!section) {
        section = await prisma.examSection.create({
          data: {
            examId: id,
            type,
            heading: sectionHeading(exam.config.grade, type, exam.config.language, exam.config.stream),
            order: type === "PART_ONE" ? 2 : 3,
            content: "{}",
          },
        });
      }
      await prisma.task.deleteMany({ where: { sectionId: section.id } });
      const primary = sets[0];
      for (let i = 0; i < primary.length; i++) {
        const task = primary[i] as GeneratedTask;
        const candidates = sets.slice(1).map((s) => s[i]).filter(Boolean);
        await prisma.task.create({
          data: {
            sectionId: section.id,
            skill: task.skill ?? null,
            prompt: task.prompt,
            instruction: task.instruction,
            answer: task.answer ?? null,
            marks: task.marks,
            order: i,
            family: task.family ?? null,
            tableData: task.table ? JSON.stringify(task.table) : null,
            candidates: JSON.stringify(candidates),
          },
        });
      }
      await log("OK");
      await track(type === "PART_ONE" ? "part_one_generated" : "part_two_generated", { userId: user.id, examId: id });
      await captureRevision(id, type === "PART_ONE" ? "Part One generated" : "Text exploration generated");
    } else if (type === "WRITING") {
      const cands = await generateWritingCandidates(ctx);
      const singleTopic = !!ctx.guide.writing.singleTopic;
      const v = validateCandidate("WRITING", cands[0], undefined, singleTopic ? { singleTopic: true } : undefined);
      if (!v.ok) {
        await log("ERROR", v.issues.join("; "));
        await track("generation_failed", { userId: user.id, examId: id, meta: { type, issues: v.issues } });
        return NextResponse.json({ error: v.issues.join(" ") }, { status: 422 });
      }
      let section = sectionOf(exam.sections, "WRITING");
      if (!section) {
        section = await prisma.examSection.create({
          data: { examId: id, type: "WRITING", heading: sectionHeading(exam.config.grade, "WRITING", exam.config.language, exam.config.stream), order: 4, content: "{}" },
        });
      }
      await prisma.topic.deleteMany({ where: { sectionId: section.id } });
      const guidedSets = cands.map((c) => c.guided);
      await prisma.topic.create({
        data: {
          sectionId: section.id,
          kind: "GUIDED",
          title: guidedSets[0].title,
          situation: guidedSets[0].situation,
          instruction: guidedSets[0].instruction,
          keywords: guidedSets[0].keywords ?? null,
          form: guidedSets[0].form,
          marks: guidedSets[0].marks,
          order: 0,
          candidates: JSON.stringify(guidedSets.slice(1)),
        },
      });
      if (!singleTopic) {
        const freeSets = cands.map((c) => c.free).filter(Boolean);
        if (freeSets.length > 0 && freeSets[0]) {
          await prisma.topic.create({
            data: {
              sectionId: section.id,
              kind: "FREE",
              title: freeSets[0].title,
              situation: freeSets[0].situation,
              instruction: freeSets[0].instruction,
              keywords: null,
              form: freeSets[0].form,
              marks: freeSets[0].marks,
              order: 1,
              candidates: JSON.stringify(freeSets.slice(1)),
            },
          });
        }
      }
      await log("OK");
      await track("writing_generated", { userId: user.id, examId: id });
      await captureRevision(id, "Writing generated");
    } else if (type === "REWRITE") {
      const textSection = sectionOf(exam.sections, "TEXT");
      if (!textSection?.content) {
        return NextResponse.json({ error: "Generate the reading text first." }, { status: 400 });
      }
      const current = JSON.parse(textSection.content);
      if (!current.text) {
        return NextResponse.json({ error: "Generate the reading text first." }, { status: 400 });
      }
      const target = body.target === "harder" ? "harder" : "simpler";
      const rewriteResult = await generateRewriteCandidates(ctx, {
        text: current.text,
        title: current.title,
        target,
      });
      const rewritten = rewriteResult[0];
      const v = validateCandidate("TEXT", rewritten);
      if (!v.ok) {
        await log("ERROR", v.issues.join("; "));
        await track("generation_failed", { userId: user.id, examId: id, meta: { type, issues: v.issues } });
        return NextResponse.json({ error: v.issues.join(" ") }, { status: 422 });
      }
      // Simplify / Make harder propose: the rewrites go to the alternatives box and
      // the current text stays untouched until the teacher selects one (PRD 15.2).
      current.candidates = [...(current.candidates ?? []), ...rewriteResult.map(textOnly)];
      await prisma.examSection.update({
        where: { id: textSection.id },
        data: { content: JSON.stringify(current) },
      });
      await log("OK");
      await track("text_rewritten", { userId: user.id, examId: id, meta: { target } });
      await captureRevision(id, target === "simpler" ? "Simplified text" : "Hardened text");
    } else if (type === "TASK_ALT" && body.taskId) {
      const task = await prisma.task.findFirst({
        where: { id: body.taskId, section: { examId: id } },
        include: { section: true },
      });
      if (!task) return NextResponse.json({ error: "Task not found." }, { status: 404 });
      const sets =
        task.section.type === "PART_ONE"
          ? await generatePartOneCandidates(ctx)
          : await generateTextExplorationCandidates(ctx);
      const index = task.order;
      const candidates = sets.slice(1).map((s) => s[index]).filter(Boolean);
      await prisma.task.update({ where: { id: task.id }, data: { candidates: JSON.stringify(candidates) } });
      await log("OK");
      await track("task_replaced", { userId: user.id, examId: id, meta: { kind: "generate_more" } });
    } else if (type === "TOPIC_ALT" && body.topicId) {
      const topic = await prisma.topic.findFirst({ where: { id: body.topicId, section: { examId: id } } });
      if (!topic) return NextResponse.json({ error: "Topic not found." }, { status: 404 });
      const cands = await generateWritingCandidates(ctx);
      const topicSets = topic.kind === "GUIDED"
        ? cands.map((c) => c.guided)
        : cands.map((c) => c.free).filter(Boolean);
      const sets = (topicSets.length > 0 ? topicSets.slice(1) : []);
      await prisma.topic.update({ where: { id: topic.id }, data: { candidates: JSON.stringify(sets) } });
      await log("OK");
      await track("topic_replaced", { userId: user.id, examId: id, meta: { kind: "generate_more" } });
    } else {
      return NextResponse.json({ error: "Unsupported generation type." }, { status: 400 });
    }

    const dto = await loadExamDto(id, user.id);
    return NextResponse.json(dto);
  } catch (e: any) {
    if (e?.message === "UNAUTHORIZED") return NextResponse.json({ error: "Please log in." }, { status: 401 });
    const msg = e?.message?.includes("not") ? e.message : "Generation failed. Please try again.";
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
