import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { requireUser } from "@/lib/auth";
import { loadExamDto } from "@/lib/serialize";
import { buildContext, generateTextCandidates, generatePartOneCandidates, generateTextExplorationCandidates, generateWritingCandidates, validateCandidate, providerName } from "@/lib/generate";
import { track } from "@/lib/events";
import type { GeneratedTask, GeneratedTopic } from "@/types";

export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const user = await requireUser();
    const { id } = await params;
    const exam = await prisma.exam.findFirst({
      where: { id, userId: user.id },
      include: { config: true, sections: { include: { tasks: true, topics: true } } },
    });
    if (!exam) return NextResponse.json({ error: "Exam not found." }, { status: 404 });
    if (!exam.config) return NextResponse.json({ error: "Set the exam parameters first." }, { status: 400 });

    const body = (await req.json()) as { type: string; taskId?: string; topicId?: string };
    const type = body.type;
    const provider = providerName();

    const ctx = buildContext({
      level: exam.config.level,
      grade: exam.config.grade,
      stream: exam.config.stream,
      length: exam.config.length,
      unit: exam.config.unit,
      topic: exam.config.topic,
      examId: exam.id,
    });

    const log = (status: string, error?: string) =>
      prisma.generation.create({ data: { examId: id, type, provider, status, error } });

    const sectionOf = (sections: any[], type: string) =>
      sections.find((s: any) => s.type === type);

    if (type === "TEXT") {
      const candidates = generateTextCandidates(ctx);
      const v = validateCandidate("TEXT", { text: candidates[0].text, title: candidates[0].title });
      if (!v.ok) {
        await log("ERROR", v.issues.join("; "));
        await track("generation_failed", { userId: user.id, examId: id, meta: { type, issues: v.issues } });
        return NextResponse.json({ error: v.issues.join(" ") }, { status: 422 });
      }
      let section = sectionOf(exam.sections, "TEXT");
      if (!section) {
        section = await prisma.examSection.create({
          data: { examId: id, type: "TEXT", heading: "A. Reading Comprehension", order: 1, content: "{}" },
        });
      } else {
        const old = section.content ? JSON.parse(section.content) : {};
        if (old.text) candidates.push({ title: old.title ?? old.textTitle, text: old.text });
      }
      await prisma.examSection.update({
        where: { id: section.id },
        data: { content: JSON.stringify({ title: candidates[0].title, text: candidates[0].text, candidates }) },
      });
      await prisma.source.deleteMany({ where: { examId: id, sectionId: section.id } }).catch(() => {});
      await prisma.source.create({
        data: {
          examId: id,
          sectionId: section.id,
          title: "Exai original passage",
          author: null,
          publication: null,
          url: null,
          accessedAt: new Date().toISOString().slice(0, 10),
          adaptationNote: "Original passage generated by Exai. No external source was used for this draft.",
          isExternal: false,
        },
      });
      await log("OK");
      await track("text_generated", { userId: user.id, examId: id });
    } else if (type === "PART_ONE" || type === "TEXT_EXPLORATION") {
      const sets = type === "PART_ONE" ? generatePartOneCandidates(ctx) : generateTextExplorationCandidates(ctx);
      const v = validateCandidate(type, sets[0]);
      if (!v.ok) {
        await log("ERROR", v.issues.join("; "));
        await track("generation_failed", { userId: user.id, examId: id, meta: { type, issues: v.issues } });
        return NextResponse.json({ error: v.issues.join(" ") }, { status: 422 });
      }
      let section = sectionOf(exam.sections, type);
      if (!section) {
        section = await prisma.examSection.create({
          data: {
            examId: id,
            type,
            heading: type === "PART_ONE" ? "A. Reading Comprehension" : "B. Text exploration",
            order: type === "PART_ONE" ? 2 : 3,
            content: "{}",
          },
        });
      }
      await prisma.task.deleteMany({ where: { sectionId: section.id } });
      const primary = sets[0];
      for (let i = 0; i < primary.length; i++) {
        const task = primary[i] as GeneratedTask;
        const candidates = sets.slice(1).map((s) => s[i]).filter(Boolean);
        await prisma.task.create({
          data: {
            sectionId: section.id,
            skill: task.skill ?? null,
            prompt: task.prompt,
            instruction: task.instruction,
            answer: task.answer ?? null,
            marks: task.marks,
            order: i,
            candidates: JSON.stringify(candidates),
          },
        });
      }
      await log("OK");
      await track(type === "PART_ONE" ? "part_one_generated" : "part_two_generated", { userId: user.id, examId: id });
    } else if (type === "WRITING") {
      const cands = generateWritingCandidates(ctx);
      const v = validateCandidate("WRITING", cands[0]);
      if (!v.ok) {
        await log("ERROR", v.issues.join("; "));
        await track("generation_failed", { userId: user.id, examId: id, meta: { type, issues: v.issues } });
        return NextResponse.json({ error: v.issues.join(" ") }, { status: 422 });
      }
      let section = sectionOf(exam.sections, "WRITING");
      if (!section) {
        section = await prisma.examSection.create({
          data: { examId: id, type: "WRITING", heading: "C. Written expression", order: 4, content: "{}" },
        });
      }
      await prisma.topic.deleteMany({ where: { sectionId: section.id } });
      const guidedSets = cands.map((c) => c.guided);
      const freeSets = cands.map((c) => c.free);
      await prisma.topic.create({
        data: {
          sectionId: section.id,
          kind: "GUIDED",
          title: guidedSets[0].title,
          situation: guidedSets[0].situation,
          instruction: guidedSets[0].instruction,
          keywords: guidedSets[0].keywords ?? null,
          form: guidedSets[0].form,
          marks: guidedSets[0].marks,
          order: 0,
          candidates: JSON.stringify(guidedSets.slice(1)),
        },
      });
      await prisma.topic.create({
        data: {
          sectionId: section.id,
          kind: "FREE",
          title: freeSets[0].title,
          situation: freeSets[0].situation,
          instruction: freeSets[0].instruction,
          keywords: null,
          form: freeSets[0].form,
          marks: freeSets[0].marks,
          order: 1,
          candidates: JSON.stringify(freeSets.slice(1)),
        },
      });
      await log("OK");
      await track("writing_generated", { userId: user.id, examId: id });
    } else if (type === "TASK_ALT" && body.taskId) {
      const task = await prisma.task.findFirst({
        where: { id: body.taskId, section: { examId: id } },
        include: { section: true },
      });
      if (!task) return NextResponse.json({ error: "Task not found." }, { status: 404 });
      const sets =
        task.section.type === "PART_ONE"
          ? generatePartOneCandidates(ctx)
          : generateTextExplorationCandidates(ctx);
      const index = task.order;
      const candidates = sets.slice(1).map((s) => s[index]).filter(Boolean);
      await prisma.task.update({ where: { id: task.id }, data: { candidates: JSON.stringify(candidates) } });
      await log("OK");
      await track("task_replaced", { userId: user.id, examId: id, meta: { kind: "generate_more" } });
    } else if (type === "TOPIC_ALT" && body.topicId) {
      const topic = await prisma.topic.findFirst({ where: { id: body.topicId, section: { examId: id } } });
      if (!topic) return NextResponse.json({ error: "Topic not found." }, { status: 404 });
      const cands = generateWritingCandidates(ctx);
      const sets = (topic.kind === "GUIDED" ? cands.map((c) => c.guided) : cands.map((c) => c.free)).slice(1);
      await prisma.topic.update({ where: { id: topic.id }, data: { candidates: JSON.stringify(sets) } });
      await log("OK");
      await track("topic_replaced", { userId: user.id, examId: id, meta: { kind: "generate_more" } });
    } else {
      return NextResponse.json({ error: "Unsupported generation type." }, { status: 400 });
    }

    const dto = await loadExamDto(id, user.id);
    return NextResponse.json(dto);
  } catch (e: any) {
    if (e?.message === "UNAUTHORIZED") return NextResponse.json({ error: "Please log in." }, { status: 401 });
    const msg = e?.message?.includes("not") ? e.message : "Generation failed. Please try again.";
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
